# Dockerfile used to provide and environment to run the predictor

FROM python:3.7-slim

WORKDIR /usr/src/predictor
ENV params predictor_params.txt

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["python", "./predictor.py", "./params_docker.txt" ]
