# Dockerfile used to provide and environment to run the logger

FROM python:3.7-slim

WORKDIR /usr/src/logger

COPY Logger/requirements.txt ./
RUN pip3 install --upgrade pip
RUN pip install --upgrade pip setuptools wheel
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD python3 Logger/logger.py --broker-list localhost:9092,kafka-service:9092

