# Dockerfile used to provide and environment to run the learner

FROM python:3.7-slim

WORKDIR /usr/src/learner

COPY requirements.txt ./
RUN pip3 install --upgrade pip
RUN pip install --upgrade pip setuptools wheel
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["python", "./learner.py", "./params_docker.txt" ]



